/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOauthSquareCallbackRouteImport } from './routes/api/oauth/square/callback'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google/callback'
import { Route as ApiOauthCalendlyCallbackRouteImport } from './routes/api/oauth/calendly/callback'
import { Route as ApiOauthAcuityCallbackRouteImport } from './routes/api/oauth/acuity/callback'
import { Route as ApiOauthZohoCallbackRouteImport } from './routes/api/oauth/zoho/callback'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthSquareCallbackRoute = ApiOauthSquareCallbackRouteImport.update({
  id: '/api/oauth/square/callback',
  path: '/api/oauth/square/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCalendlyCallbackRoute =
  ApiOauthCalendlyCallbackRouteImport.update({
    id: '/api/oauth/calendly/callback',
    path: '/api/oauth/calendly/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthAcuityCallbackRoute = ApiOauthAcuityCallbackRouteImport.update({
  id: '/api/oauth/acuity/callback',
  path: '/api/oauth/acuity/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthZohoCallbackRoute = ApiOauthZohoCallbackRouteImport.update({
  id: '/api/oauth/zoho/callback',
  path: '/api/oauth/zoho/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/platforms': typeof PlatformsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/api/oauth/acuity/callback': typeof ApiOauthAcuityCallbackRoute
  '/api/oauth/zoho/callback': typeof ApiOauthZohoCallbackRoute
  '/api/oauth/calendly/callback': typeof ApiOauthCalendlyCallbackRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/square/callback': typeof ApiOauthSquareCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/platforms': typeof PlatformsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/api/oauth/acuity/callback': typeof ApiOauthAcuityCallbackRoute
  '/api/oauth/zoho/callback': typeof ApiOauthZohoCallbackRoute
  '/api/oauth/calendly/callback': typeof ApiOauthCalendlyCallbackRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/square/callback': typeof ApiOauthSquareCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/platforms': typeof PlatformsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/api/oauth/acuity/callback': typeof ApiOauthAcuityCallbackRoute
  '/api/oauth/zoho/callback': typeof ApiOauthZohoCallbackRoute
  '/api/oauth/calendly/callback': typeof ApiOauthCalendlyCallbackRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/square/callback': typeof ApiOauthSquareCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/login'
    | '/platforms'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/support'
    | '/api/oauth/acuity/callback'
    | '/api/oauth/zoho/callback'
    | '/api/oauth/calendly/callback'
    | '/api/oauth/google/callback'
    | '/api/oauth/square/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/login'
    | '/platforms'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/support'
    | '/api/oauth/acuity/callback'
    | '/api/oauth/zoho/callback'
    | '/api/oauth/calendly/callback'
    | '/api/oauth/google/callback'
    | '/api/oauth/square/callback'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/login'
    | '/platforms'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/support'
    | '/api/oauth/acuity/callback'
    | '/api/oauth/zoho/callback'
    | '/api/oauth/calendly/callback'
    | '/api/oauth/google/callback'
    | '/api/oauth/square/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  LoginRoute: typeof LoginRoute
  PlatformsRoute: typeof PlatformsRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  ApiOauthAcuityCallbackRoute: typeof ApiOauthAcuityCallbackRoute
  ApiOauthZohoCallbackRoute: typeof ApiOauthZohoCallbackRoute
  ApiOauthCalendlyCallbackRoute: typeof ApiOauthCalendlyCallbackRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthSquareCallbackRoute: typeof ApiOauthSquareCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/square/callback': {
      id: '/api/oauth/square/callback'
      path: '/api/oauth/square/callback'
      fullPath: '/api/oauth/square/callback'
      preLoaderRoute: typeof ApiOauthSquareCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/calendly/callback': {
      id: '/api/oauth/calendly/callback'
      path: '/api/oauth/calendly/callback'
      fullPath: '/api/oauth/calendly/callback'
      preLoaderRoute: typeof ApiOauthCalendlyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/acuity/callback': {
      id: '/api/oauth/acuity/callback'
      path: '/api/oauth/acuity/callback'
      fullPath: '/api/oauth/acuity/callback'
      preLoaderRoute: typeof ApiOauthAcuityCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/zoho/callback': {
      id: '/api/oauth/zoho/callback'
      path: '/api/oauth/zoho/callback'
      fullPath: '/api/oauth/zoho/callback'
      preLoaderRoute: typeof ApiOauthZohoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  LoginRoute: LoginRoute,
  PlatformsRoute: PlatformsRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  ApiOauthAcuityCallbackRoute: ApiOauthAcuityCallbackRoute,
  ApiOauthZohoCallbackRoute: ApiOauthZohoCallbackRoute,
  ApiOauthCalendlyCallbackRoute: ApiOauthCalendlyCallbackRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthSquareCallbackRoute: ApiOauthSquareCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
